dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
  default: development
wallets:
  from_key: ${PRIVATE_KEY}